# Catching More Errors!

One additional change to our program.

**Task**
Take the console.log() statement and extract it into a separate helper func to allow us to leave the promise body more compact than it is.

1. Write new func at the bottom called `logTodo` as an arrow func, pass in the x3 properties, cut/past the consol.log() inside of it.
2. Now call that new func from the response arrow func, pass in the x3 properties.
3. Now we made errors as the x3 parameters inside the logTodo func but this is not flagged up until we ran the app again. If we had written TS we would of found the error before we ran app.
4. To fix this we now write TS > write type annotation/TS syntax.
The id has to be a number, the title has to be a string, the completed property has to be a boolean.
```js
const logTodo = (id: number, title: string, completed: boolean) => {
  ...
}
```

5. The completed flag/property is underlined in red and when we hover over it we get error msg to let us know that we can't assign a boolean to a parma of type string.
6. logTodo func says the second argument has to be a string NOT a boolean. Now we made mistake in the order of arguments when we called this logTodo func inside of the response func and we just need to switch the two around.
7. Run app again and I see the correct result in the terminal. This is why we like to use TypeScript.
